# Generated by Django 4.2.29 on 2026-03-17 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POCPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='插件名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('vuln_type', models.CharField(max_length=50, verbose_name='漏洞类型')),
                ('code', models.TextField(verbose_name='插件代码')),
                ('version', models.CharField(default='1.0', max_length=50, verbose_name='版本')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'POC插件',
                'verbose_name_plural': 'POC插件',
                'db_table': 'poc_plugins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200, verbose_name='主机')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('service', models.CharField(blank=True, max_length=100, verbose_name='服务')),
                ('state', models.CharField(choices=[('open', '开放'), ('closed', '关闭'), ('filtered', '过滤')], max_length=20, verbose_name='状态')),
                ('banner', models.TextField(blank=True, verbose_name='横幅')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '端口扫描结果',
                'verbose_name_plural': '端口扫描结果',
                'db_table': 'port_scan_results',
                'ordering': ['port'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='报告标题')),
                ('content', models.TextField(blank=True, verbose_name='报告内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='文件路径')),
            ],
            options={
                'verbose_name': '报告',
                'verbose_name_plural': '报告',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='规则名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('rule_type', models.CharField(choices=[('regex', '正则表达式'), ('keyword', '关键词'), ('header', '响应头'), ('payload', '攻击载荷')], max_length=20, verbose_name='规则类型')),
                ('content', models.TextField(verbose_name='规则内容')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '扫描规则',
                'verbose_name_plural': '扫描规则',
                'db_table': 'scan_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('scan_type', models.CharField(choices=[('full', '全面扫描'), ('quick', '快速扫描'), ('custom', '自定义扫描')], default='full', max_length=20, verbose_name='扫描类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='配置')),
                ('critical_count', models.IntegerField(default=0, verbose_name='严重漏洞数')),
                ('high_count', models.IntegerField(default=0, verbose_name='高危漏洞数')),
                ('medium_count', models.IntegerField(default=0, verbose_name='中危漏洞数')),
                ('low_count', models.IntegerField(default=0, verbose_name='低危漏洞数')),
                ('info_count', models.IntegerField(default=0, verbose_name='信息漏洞数')),
            ],
            options={
                'verbose_name': '扫描任务',
                'verbose_name_plural': '扫描任务',
                'db_table': 'scan_tasks',
                'ordering': ['-start_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='网站名称')),
                ('url', models.URLField(max_length=500, verbose_name='网站URL')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '未活跃')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网站',
                'verbose_name_plural': '网站',
                'db_table': 'sites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='漏洞名称')),
                ('vuln_type', models.CharField(choices=[('sql_injection', 'SQL注入'), ('xss', '跨站脚本'), ('weak_password', '弱口令'), ('path_traversal', '路径遍历'), ('command_injection', '命令注入'), ('csrf', '跨站请求伪造'), ('xxe', 'XML外部实体注入'), ('ssrf', '服务端请求伪造'), ('file_upload', '文件上传漏洞'), ('info_disclosure', '信息泄露'), ('open_redirect', '开放重定向'), ('other', '其他')], max_length=50, verbose_name='漏洞类型')),
                ('severity', models.CharField(choices=[('critical', '严重'), ('high', '高危'), ('medium', '中危'), ('low', '低危'), ('info', '信息')], max_length=20, verbose_name='严重程度')),
                ('url', models.URLField(max_length=1000, verbose_name='漏洞URL')),
                ('parameter', models.CharField(blank=True, max_length=200, verbose_name='参数')),
                ('payload', models.TextField(blank=True, verbose_name='攻击载荷')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('solution', models.TextField(blank=True, verbose_name='解决方案')),
                ('status', models.CharField(choices=[('open', '未修复'), ('fixed', '已修复'), ('ignored', '已忽略')], default='open', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scanner.scantask', verbose_name='扫描任务')),
            ],
            options={
                'verbose_name': '漏洞',
                'verbose_name_plural': '漏洞',
                'db_table': 'vulnerabilities',
                'ordering': ['-created_at'],
            },
        ),
    ]
